apiVersion: v1
kind: Service
metadata:
  name: js-entity-extract
spec:
  selector:
    pod: js-entity-extract
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: js-entity-extract-up
  namespace: default
data:
  prod_up: |-
    git clone https://github.com/Jaseci-Labs/jaseci.git /jaseci/
    cd /jaseci/jaseci_core/
    source install.sh
    cd /jaseci/jskit/entity_extraction
    uvicorn entity_extraction:serv_actions --host 0.0.0.0 --port 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: js-entity-extract
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: js-entity-extract
  template:
    metadata:
      labels:
        pod: js-entity-extract
      name: js-entity-extract
    spec:
      containers:
        - name: js-entity-extract
          imagePullPolicy: IfNotPresent
          image: jaseci/ai-ready-img
          resources:
            requests:
              memory: "3Gi"
          command: [bash, -c, "source script/prod_up"]
          ports:
            - containerPort: 80
          volumeMounts:
            - name: prod-script
              mountPath: /script

      volumes:
        - name: prod-script
          configMap:
            name: js-entity-extract-up
