export const componentMap: Record<Exclude<ComponentNames, 'App'>, ComponentTags> = {
  Navbar: 'jsc-nav-bar',
  NavLink: 'jsc-nav-link',
  Container: 'jsc-container',
  Row: 'jsc-row',
  Column: 'jsc-column',
  Button: 'jsc-button',
  Inputbox: 'jsc-inputbox',
  Textbox: 'jsc-textbox',
  Text: 'jsc-text',
  Card: 'jsc-card',
  DatePicker: 'jsc-date-picker',
  Divider: 'jsc-divider',
  Anchor: 'jsc-anchor',
  Chip: 'jsc-chip',
  Datagrid: 'jsc-datagrid',
  Datalist: 'jsc-datalist',
  Datarow: 'jsc-datarow',
  Dialog: 'jsc-dialog',
  Popover: 'jsc-popover',
  Tabs: 'jsc-tabs',
  Tab: 'jsc-tab',
};
