apiVersion: v1
kind: Service
metadata:
  name: js-use-qa
spec:
  selector:
    pod: js-use-qa
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: js-use-qa-up
  namespace: default
data:
  prod_up: |-
    pip install jaseci-ai-kit==$version
    uvicorn jaseci_ai_kit.use_qa:serv_actions --host 0.0.0.0 --port 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: js-use-qa
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: js-use-qa
  template:
    metadata:
      labels:
        pod: js-use-qa
      name: js-use-qa
    spec:
      containers:
        - name: js-use-qa
          imagePullPolicy: IfNotPresent
          image: jaseci/jaseci-ai-kit:latest
          resources:
            requests:
              memory: "3Gi"
            limits:
              memory: "3Gi"
          command: [bash, -c, "source script/prod_up"]
          ports:
            - containerPort: 80
          volumeMounts:
            - name: prod-script
              mountPath: /script

      volumes:
        - name: prod-script
          configMap:
            name: js-use-qa-up
