#!/home/jac/repos/jac-python/.venv/bin/python
"""Emit CPython 3.14.7 bytecode goldens for raise-from variants.

This script is generate-only: it uses host compile()/dis and has no Jac runtime
or repository writes. Run with the repository's pinned .venv interpreter.
"""
from __future__ import annotations

import dis
import json
import sys
from typing import Any


FIXTURES: list[tuple[str, str]] = [
    (
        "top_level_raise_instance_from_instance",
        """def f():
    raise ValueError('x') from TypeError('c')
""",
    ),
    (
        "raise_instance_from_none",
        """def f():
    raise ValueError('x') from None
""",
    ),
    (
        "raise_from_inside_except_explicit_cause",
        """def f():
    try:
        raise ValueError('original')
    except ValueError:
        raise TypeError('replacement') from KeyError('cause')
""",
    ),
    (
        "implicit_chaining_inside_except",
        """def f():
    try:
        raise ValueError('original')
    except ValueError:
        raise TypeError('replacement')
""",
    ),
    (
        "bare_raise_inside_except",
        """def f():
    try:
        raise ValueError('original')
    except ValueError:
        raise
""",
    ),
    (
        "raise_class_from_err",
        """def f(err):
    raise ValueError from err
""",
    ),
    (
        "raise_instance_from_err",
        """def f(err):
    raise ValueError('x') from err
""",
    ),
    (
        "raise_from_inside_finally",
        """def f():
    try:
        marker = 1
    finally:
        raise ValueError('final') from TypeError('cause')
""",
    ),
]


def nested_code_by_name(code: Any, name: str) -> Any:
    """Return the first recursively nested code object with co_name == name."""
    if getattr(code, "co_name", None) == name:
        return code
    for const in getattr(code, "co_consts", ()):
        if hasattr(const, "co_code"):
            found = nested_code_by_name(const, name)
            if found is not None:
                return found
    return None


def instruction_record(ins: dis.Instruction) -> dict[str, Any]:
    return {
        "offset": ins.offset,
        "opname": ins.opname,
        "opcode": ins.opcode,
        "arg": ins.arg,
        "argval": repr(ins.argval),
        "argrepr": ins.argrepr,
        "starts_line": ins.starts_line,
        "is_jump_target": ins.is_jump_target,
    }


def exception_record(entry: Any) -> dict[str, Any]:
    return {
        "start": entry.start,
        "end": entry.end,
        "target": entry.target,
        "depth": entry.depth,
        "lasti": entry.lasti,
    }


def build_record(name: str, source: str) -> dict[str, Any]:
    module_code = compile(source, "<raise-from-oracle>", "exec")
    function_code = nested_code_by_name(module_code, "f")
    if function_code is None:
        raise AssertionError(f"fixture {name!r} did not define f")

    # Request cache entries where the interpreter exposes them; CPython 3.14
    # may fold inline cache units into the displayed instruction stream.
    instructions = [
        instruction_record(i)
        for i in dis.get_instructions(function_code, show_caches=True)
    ]
    entries = [exception_record(e) for e in dis.Bytecode(function_code).exception_entries]
    assertion_like = [i["opname"] for i in instructions if "ASSERTION_ERROR" in i["opname"]]
    return {
        "name": name,
        "source": source,
        "code_name": function_code.co_name,
        "co_flags": hex(function_code.co_flags),
        "co_flags_int": function_code.co_flags,
        "co_stacksize": function_code.co_stacksize,
        "co_code": function_code.co_code.hex(),
        "co_exceptiontable": function_code.co_exceptiontable.hex(),
        "instructions": instructions,
        "exception_entries": entries,
        "assertion_error_like_opnames": assertion_like,
        "assertion_error_note": (
            "No LOAD_ASSERTION_ERROR-like opcode is emitted for this raise fixture."
            if not assertion_like
            else "Assertion-error-like opcode(s) present: " + ", ".join(assertion_like)
        ),
    }


def render_instruction(ins: dict[str, Any]) -> str:
    arg = "" if ins["arg"] is None else f" arg={ins['arg']}"
    argrepr = f" {ins['argrepr']}" if ins["argrepr"] else ""
    line = "" if ins["starts_line"] is None else f" line={ins['starts_line']}"
    target = " ->target" if ins["is_jump_target"] else ""
    return f"{ins['offset']:>3}: {ins['opname']:<24}{arg}{argrepr}{line}{target}"


def render_markdown(records: list[dict[str, Any]]) -> str:
    out: list[str] = [
        "# Band 6 `raise ... from` CPython oracle goldens",
        "",
        "Generated by `dump.py` with `/home/jac/repos/jac-python/.venv/bin/python`.",
        "The code object recorded for each fixture is nested function `f`.",
        "",
    ]
    for rec in records:
        out.extend(
            [
                f"## `{rec['name']}`",
                "",
                "### Source",
                "",
                "```python",
                rec["source"].rstrip("\\n"),
                "```",
                "",
                f"- `co_flags`: `{rec['co_flags']}` ({rec['co_flags_int']})",
                f"- `co_stacksize`: `{rec['co_stacksize']}`",
                f"- `co_code.hex()`: `{rec['co_code']}`",
                f"- `co_exceptiontable.hex()`: `{rec['co_exceptiontable']}`",
                f"- assertion handling: {rec['assertion_error_note']}",
                "",
                "### Disassembly",
                "",
                "```text",
            ]
        )
        out.extend(render_instruction(i) for i in rec["instructions"])
        out.extend(["```", "", "### Exception entries", ""])
        if rec["exception_entries"]:
            out.extend(
                f"- start={e['start']} end={e['end']} target={e['target']} "
                f"depth={e['depth']} lasti={e['lasti']}"
                for e in rec["exception_entries"]
            )
        else:
            out.append("- none")
        out.append("")
    return "\n".join(out)


def main() -> None:
    records = [build_record(name, source) for name, source in FIXTURES]
    payload = {
        "interpreter": sys.executable,
        "python_version": sys.version,
        "fixtures": records,
    }
    # JSON is the machine-readable golden; markdown is the paste/read reference.
    print(json.dumps(payload, indent=2, sort_keys=False))
    print("\n" + render_markdown(records), file=sys.stderr)


if __name__ == "__main__":
    main()
