apiVersion: v1
kind: Service
metadata:
  name: js-biencoder
spec:
  selector:
    pod: js-biencoder
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: js-biencoder-up
  namespace: default
data:
  prod_up: |-
    git clone https://github.com/Jaseci-Labs/jaseci.git /jaseci/
    cd /jaseci/jaseci_core/
    source install.sh
    cd /jaseci/jskit/encoders
    uvicorn bi:app --host 0.0.0.0 --port 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: js-biencoder
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: js-biencoder
  template:
    metadata:
      labels:
        pod: js-biencoder
      name: js-biencoder
    spec:
      containers:
        - name: js-biencoder
          imagePullPolicy: IfNotPresent
          image: jaseci/ai-ready-img
          resources:
            requests:
              memory: "3Gi"
            limits:
              memory: "3Gi"
          command: [bash, -c, "source script/prod_up"]
          ports:
            - containerPort: 80
          volumeMounts:
            - name: prod-script
              mountPath: /script

      volumes:
        - name: prod-script
          configMap:
            name: js-biencoder-up
