"""Single source of truth for jac's on-disk cache and data roots.

Pure Python with no jac dependencies, so it is importable during bootstrap,
before the jac0core ``.jac`` modules have been transpiled. Every cache in the
tree derives its directory from here; the only permitted duplicate of the
platform triplet is ``jaclang/dist/fused/materialize.jac``, which runs inside
the launcher before CPython exists and must mirror ``cache_root`` exactly.

Platform roots (cache):
    Linux:   ~/.cache/jac/            ($XDG_CACHE_HOME honored)
    macOS:   ~/Library/Caches/jac/
    Windows: %LOCALAPPDATA%/jac/cache/
Platform roots (data, for durable state that must survive a cache purge):
    Linux:   ~/.local/share/jac/      ($XDG_DATA_HOME honored)
    macOS:   ~/Library/Application Support/jac/
    Windows: %LOCALAPPDATA%/jac/data/

``JAC_CACHE_DIR`` / ``JAC_DATA_DIR`` override the respective root wholesale.
These are the only two environment variables the cache layer honors for
location; per-store overrides do not exist by design.

Store layout under the cache root (one directory per registered store)::

    CACHEDIR.TAG   modules/  bootstrap/  kernels/  stubs/  runtimes/
    apps/  bin/  models/  browser/  pg/

Atomic publication: every write goes through ``atomic_publish`` (blob) or
``atomic_publish_dir`` (directory entry) so a reader can never observe a torn
entry, parallel writers cannot collide on a temp name (pid-suffixed via
``with_name``, never ``with_suffix``), and overwrite works on Windows
(``os.replace``, never ``rename``).
"""

import os
import shutil
import sys
from pathlib import Path

CACHEDIR_TAG = (
    "Signature: 8a477f597d28d172789f06886806bc55\n"
    "# This directory contains cached data generated by jac.\n"
    "# Everything in it can be regenerated; backup tools may skip it.\n"
)


def cache_root() -> Path:
    """Return the platform-appropriate global cache root, creating it."""
    override = os.environ.get("JAC_CACHE_DIR")
    if override:
        root = Path(override)
    elif sys.platform == "win32":
        base = Path(os.environ.get("LOCALAPPDATA", Path.home() / "AppData" / "Local"))
        root = base / "jac" / "cache"
    elif sys.platform == "darwin":
        root = Path.home() / "Library" / "Caches" / "jac"
    else:
        xdg = os.environ.get("XDG_CACHE_HOME")
        base = Path(xdg) if xdg else (Path.home() / ".cache")
        root = base / "jac"
    _ensure_root(root)
    return root


def writable_cache_root() -> Path:
    """Cache root with a write probe, falling back to a per-uid tmp dir.

    For callers that must succeed on read-only homes (the launcher's runtime
    extraction). Mirrored by ``dist/fused/materialize.jac``.
    """
    root = cache_root()
    if _dir_writable(root):
        return root
    tmp = os.environ.get("TMPDIR") or "/tmp"
    uid = os.getuid() if hasattr(os, "getuid") else 0
    fallback = Path(tmp) / f"jac-cache-{uid}"
    _ensure_root(fallback)
    return fallback


def data_root() -> Path:
    """Durable-state root: survives ``jac cache purge`` by construction."""
    override = os.environ.get("JAC_DATA_DIR")
    if override:
        root = Path(override)
    elif sys.platform == "win32":
        base = Path(os.environ.get("LOCALAPPDATA", Path.home() / "AppData" / "Local"))
        root = base / "jac" / "data"
    elif sys.platform == "darwin":
        root = Path.home() / "Library" / "Application Support" / "jac"
    else:
        xdg = os.environ.get("XDG_DATA_HOME")
        base = Path(xdg) if xdg else (Path.home() / ".local" / "share")
        root = base / "jac"
    root.mkdir(parents=True, exist_ok=True)
    return root


def store_dir(name: str) -> Path:
    """Directory for one named store under the cache root, creating it."""
    path = cache_root() / name
    path.mkdir(parents=True, exist_ok=True)
    return path


def data_dir(name: str) -> Path:
    """Directory for one named durable store under the data root."""
    path = data_root() / name
    path.mkdir(parents=True, exist_ok=True)
    return path


def pid_tmp(path: Path) -> Path:
    """Sibling temp path for ``path``, unique per process.

    Uses ``with_name`` so dotted entry names (version strings, digests) are
    appended to, never truncated; ``with_suffix`` here was the #8655 bug.
    """
    return path.with_name(f".{path.name}.{os.getpid()}.tmp")


def atomic_publish(path: Path, data: bytes) -> None:
    """Publish ``data`` at ``path`` atomically (write temp, ``os.replace``)."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = pid_tmp(path)
    try:
        tmp.write_bytes(data)
        os.replace(tmp, path)
    finally:
        try:
            tmp.unlink()
        except OSError:
            pass


def atomic_publish_text(path: Path, text: str) -> None:
    """Publish ``text`` at ``path`` atomically."""
    atomic_publish(path, text.encode())


def atomic_publish_dir(tmp_dir: Path, dest: Path) -> bool:
    """Publish a fully-populated directory entry by rename.

    Returns True if this process's tree became (or already was) the published
    entry. A concurrent winner is tolerated: if the rename fails because
    ``dest`` exists, the temp tree is discarded and the existing entry stands,
    so racing materializers of the same content-addressed key both succeed.
    """
    tmp_dir = Path(tmp_dir)
    dest = Path(dest)
    dest.parent.mkdir(parents=True, exist_ok=True)
    try:
        os.rename(tmp_dir, dest)
        return True
    except OSError:
        won = dest.exists()
        shutil.rmtree(tmp_dir, ignore_errors=True)
        return won


def lock_path(path: Path):
    """Advisory exclusive lock for check-then-act publication.

    Returns an opaque handle for ``unlock``; returns None where locking is
    unavailable (the caller proceeds unlocked, protected by atomic publish).
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        handle = open(path, "a+")
    except OSError:
        return None
    try:
        if sys.platform == "win32":
            import msvcrt

            handle.seek(0)
            msvcrt.locking(handle.fileno(), msvcrt.LK_LOCK, 1)
        else:
            import fcntl

            fcntl.flock(handle.fileno(), fcntl.LOCK_EX)
    except OSError:
        handle.close()
        return None
    return handle


def unlock(handle) -> None:
    """Release a lock taken with ``lock_path``."""
    if handle is None:
        return
    try:
        if sys.platform == "win32":
            import msvcrt

            handle.seek(0)
            msvcrt.locking(handle.fileno(), msvcrt.LK_UNLCK, 1)
        else:
            import fcntl

            fcntl.flock(handle.fileno(), fcntl.LOCK_UN)
    except OSError:
        pass
    finally:
        handle.close()


def _ensure_root(root: Path) -> None:
    root.mkdir(parents=True, exist_ok=True)
    tag = root / "CACHEDIR.TAG"
    if not tag.exists():
        try:
            tag.write_text(CACHEDIR_TAG)
        except OSError:
            pass


def _dir_writable(path: Path) -> bool:
    probe = path / f".probe.{os.getpid()}"
    try:
        probe.write_bytes(b"")
        probe.unlink()
        return True
    except OSError:
        return False
