#!/usr/bin/env python3
"""D2 conversion pipeline runner: .jac pins -> classified triage report.

Executes every pin produced by ``convert_suite.py`` on jacpython's ceval using
the repo-proven bridge convention (``p2_libtest_jacpython_bridge.py``): one
generated harness ``.jac`` placed beside ``layer_p2_libtest.jac``, driven by a
single ``jac run`` subprocess with a hard timeout. Each pin prints a
machine-readable ``MARK`` line, so results are isolated per test:

- ``PASS``                guest outcome matched the host oracle
- ``GUEST-WRONG-OUTPUT``  snippet ran on jacpython's ceval but disagreed with
  the oracle (``GOT<..>`` wrong final output / ``RUN<..>`` guest exception)
- ``VM-CRASH``            the VM died mid-run; every pin after the last MARK
  is classified here
- ``TIMEOUT``             the jac invocation hit the hard limit
- ``QUARANTINED``         quarantined at conversion time (sidecar meta)

Emits a markdown triage report and updates the conformance manifest consumed
by ``conformance_dashboard.py`` (``status`` becomes ``gated`` only when every
pin passed and nothing was quarantined; ``jacpython_results`` carries the
counters the ratchet tracks).

Usage:
    .venv/bin/python jac-py/tools/diff_runner.py <pins.jac> [--report R.md]
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import unicodedata
from pathlib import Path

_HERE = Path(__file__).resolve().parent
_REPO = _HERE.parent.parent
_JAC = _REPO / ".venv" / "bin" / "jac"
_JACPYTHON_DIR = _REPO / "jac-py" / "jacpython"
_MANIFEST = _REPO / "jac-py" / "tests" / "conformance_manifest_convpipe.json"

JAC_TIMEOUT = 60  # seconds, hard limit; one jac process at a time

from convert_suite import attempt_header, file_sha256  # shared fingerprint block

TOOL_VERSION = "diff_runner-0.2.0"

_DASH_CHARS = "\u2010\u2011\u2012\u2013\u2014\u2015\u2212"
_QUOTE_MAP = {
    "\u2018": "'", "\u2019": "'", "\u201a": "'",
    "\u201c": '"', "\u201d": '"', "\u201e": '"',
}


def _sanitize_report_text(text: str) -> str:
    """Make generated markdown pass the repo's pre-commit hooks.

    The repo bans em-dashes (pygrep ``ban-em-dashes``) and lints markdown via
    ``markdownlint-cli2``; tool banners and exception text can carry dashes,
    curly quotes, and emoji. Dashes become '-', curly quotes become their
    straight equivalents, and any other non-ASCII char is kept only if it
    decomposes to ASCII under NFKD (e.g. accented letters); otherwise dropped.
    Applies to report output only -- pinned snippets are stored elsewhere with
    ``ensure_ascii`` JSON escaping and must stay byte-exact.
    """
    out: list[str] = []
    for ch in text:
        if ch in _DASH_CHARS:
            out.append("-")
        elif ch in _QUOTE_MAP:
            out.append(_QUOTE_MAP[ch])
        elif ord(ch) < 128:
            out.append(ch)
        else:
            out.append(
                unicodedata.normalize("NFKD", ch).encode("ascii", "ignore").decode("ascii")
            )
    return "".join(out)


# ---------------------------------------------------------------------------
# Harness generation + execution


def build_harness(pins: list[dict]) -> str:
    """Single-entry harness running every pinned snippet with MARK output."""
    lines = [
        "# Generated by jac-py/tools/diff_runner.py — DO NOT EDIT BY HAND.",
        "import from layer_p2_libtest { p2_libtest_run_snippet }",
        "",
        "def _mark(name: str, source: str) -> None {",
        "    (ok, detail) = p2_libtest_run_snippet(source);",
        "    if ok {",
        '        if detail == "ok" {',
        '            print("MARK PASS " + name);',
        "        } else {",
        '            print("MARK FAIL " + name + " GOT<" + repr(detail) + ">");',
        "        }",
        "    } else {",
        '        print("MARK FAIL " + name + " RUN<" + repr(detail) + ">");',
        "    }",
        "}",
        "",
        "with entry {",
    ]
    for pin in pins:
        lit = json.dumps(pin["snippet"], ensure_ascii=True)
        lines.append(f'    _mark({json.dumps(pin["ident"])}, {lit});')
    lines.append('    print("MARK ALLDONE");')
    lines.append("}")
    return "\n".join(lines) + "\n"


def run_pins(pins: list[dict]) -> tuple[list[tuple[str, str, str]], bool, str]:
    """Run all pins in one jac process.

    Returns (marks, timed_out, stderr) with each mark a
    ``(status, ident, payload)`` tuple; status in PASS|FAIL|ALLDONE|CRASH.
    """
    harness = _JACPYTHON_DIR / f"conv_harness_{os.getpid()}.jac"
    harness.write_text(build_harness(pins), encoding="utf-8")
    env = dict(os.environ)
    env["PYTHONPATH"] = str(_REPO / "jac")
    env["JAC_DEV_SOURCE"] = str(_REPO / "jac")
    marks: list[tuple[str, str, str]] = []
    timed_out = False
    stderr_tail = ""
    try:
        proc = subprocess.run(
            [str(_JAC), "run", str(harness)],
            cwd=str(_REPO),
            env=env,
            capture_output=True,
            text=True,
            timeout=JAC_TIMEOUT,
        )
        stderr_tail = (proc.stderr or "")[-2000:]
        for line in proc.stdout.splitlines():
            parts = line.strip().split(" ", 2)
            if len(parts) >= 2 and parts[0] == "MARK":
                status = parts[1]
                rest = parts[2] if len(parts) > 2 else ""
                if status == "ALLDONE":
                    marks.append((status, "", ""))
                else:
                    ident, _, payload = rest.partition(" ")
                    marks.append((status, ident, payload))
        if proc.returncode != 0 and not any(s == "ALLDONE" for s, _, _ in marks):
            marks.append(("CRASH", "", stderr_tail.strip()[:300]))
    except subprocess.TimeoutExpired:
        timed_out = True
    finally:
        harness.unlink(missing_ok=True)
    return marks, timed_out, stderr_tail


def classify(
    marks: list[tuple[str, str, str]], pinned: list[dict], timed_out: bool
) -> dict[str, dict]:
    """Assign a classification to every pinned id."""
    order = [p["ident"] for p in pinned]
    by_status = {ident: (status, payload) for status, ident, payload in marks}
    saw_alldone = any(status == "ALLDONE" for status, _, _ in marks)
    results: dict[str, dict] = {}
    crash_reason = next((p for s, n, p in marks if s == "CRASH"), "VM exited before reporting")
    crashed_at = None
    if not saw_alldone:
        reported = sum(1 for name in order if name in by_status)
        if reported < len(order):
            crashed_at = reported
    for idx, name in enumerate(order):
        got = by_status.get(name)
        if got is None:
            if timed_out:
                results[name] = {"classification": "TIMEOUT", "detail": f"jac run hit {JAC_TIMEOUT}s cap"}
            elif crashed_at is not None and idx >= crashed_at:
                results[name] = {"classification": "VM-CRASH", "detail": crash_reason}
            else:
                results[name] = {"classification": "VM-CRASH", "detail": "no MARK captured"}
            continue
        status, payload = got
        if status == "PASS":
            continue
        results[name] = {"classification": "GUEST-WRONG-OUTPUT", "detail": payload}
    return results


# ---------------------------------------------------------------------------
# Report + manifest


def write_conformance_and_result(
    outdir: Path,
    meta: dict,
    command: list[str],
    classifications: dict[str, dict],
    timed_out: bool,
    pins_path: Path,
) -> tuple[Path, Path]:
    """Emit conformance.json (pin results) + result.json (explicit data).

    A failing pin is recorded as data in result.json['failures']; the exit
    code of diff_runner mirrors status so failure is never masked by exit 0.
    """
    header = attempt_header(command)
    header["tool_version"] = TOOL_VERSION
    header["hashes"] = {
        "pins_jac": file_sha256(pins_path),
        "conversion_json": file_sha256(outdir / "conversion.json"),
        "guest_jac_sha_note": "jac_sha is the repo HEAD driving .venv/bin/jac",
    }
    stem = meta["module_stem"]
    per_pin: list[dict] = []
    for entry in meta["pins"]:
        ident = entry["ident"]
        if entry.get("status") != "pinned":
            per_pin.append({"id": ident, "status": "quarantined", "reason": entry.get("reason", "")})
            continue
        cls = classifications.get(ident)
        per_pin.append(
            {"id": ident, "status": "pass"} if cls is None else {"id": ident, "status": "fail", **cls}
        )
    for q in meta["quarantined"]:
        per_pin.append({"id": q["ident"], "status": "quarantined", "reason": q.get("reason", "")})
    conformance = {
        **header,
        "module_stem": stem,
        "counts": {
            "converted": len(meta["pins"]) + len(meta["quarantined"]),
            "runnable": len([e for e in meta["pins"] if e.get("status") == "pinned"]),
            "green": sum(1 for p in per_pin if p["status"] == "pass"),
            "quarantined": sum(1 for p in per_pin if p["status"] == "quarantined"),
        },
        "pins": per_pin,
    }
    conformance_path = outdir / "conformance.json"
    conformance_path.write_text(json.dumps(conformance, indent=2) + "\n", encoding="utf-8")

    failures = [p for p in per_pin if p["status"] == "fail"]
    infra_failed = sum(1 for p in per_pin if p["status"] == "fail"
                       and p.get("classification") == "VM-CRASH")
    result = {
        **header,
        "module_stem": stem,
        "status": "passed" if not failures and not timed_out else "failed",
        "timed_out": timed_out,
        "counts": dict(conformance["counts"], failed=len(failures), infra_failed=infra_failed),
        "failures": failures,
    }
    result_path = outdir / "result.json"
    result_path.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    return conformance_path, result_path


def build_report(
    pins_file: Path,
    meta: dict,
    elapsed_note: str,
    classifications: dict[str, dict],
) -> str:
    counts = meta["counts"]
    total_pinned = len([p for p in meta["pins"] if p.get("status") == "pinned"])
    quarantined = list(meta["quarantined"]) + [
        {"ident": p["ident"], "reason": p.get("reason", "")}
        for p in meta["pins"]
        if p.get("status") == "quarantined"
    ]
    passed = sum(1 for e in meta["pins"] if e.get("status") == "pinned" and e["ident"] not in classifications)

    lines: list[str] = []
    lines.append(f"# Triage report: `{pins_file.name}`")
    lines.append("")
    lines.append(f"- source: {meta['source_file']}")
    lines.append(f"- guest leg: {elapsed_note}")
    lines.append(
        f"- pins: **{passed} passed** / {total_pinned} run "
        f"(+{len(quarantined)} quarantined of {counts['extracted']} extracted)"
    )
    lines.append("")
    lines.append("| pin | result | got |")
    lines.append("|---|---|---|")
    for entry in meta["pins"]:
        if entry.get("status") != "pinned":
            continue
        ident = entry["ident"]
        cls = classifications.get(ident)
        if cls is None:
            lines.append(f"| {ident} | PASS | |")
        else:
            got = cls["detail"].replace("|", "\\|").replace("\n", " ")
            lines.append(f"| {ident} | {cls['classification']} | {got} |")
    lines.append("")

    if quarantined:
        lines.append("## Quarantined at conversion")
        lines.append("")
        lines.append("| test | reason |")
        lines.append("|---|---|")
        for q in quarantined:
            reason = str(q["reason"]).replace("|", "\\|").replace("\n", " ")
            lines.append(f"| {q['ident']} | {reason} |")
        lines.append("")

    failed = sorted(classifications)
    if failed:
        lines.append("## Expected vs got")
        lines.append("")
        for ident in failed:
            cls = classifications[ident]
            lines.append(f"### {ident} ({cls['classification']})")
            lines.append("- expected: host oracle = `ok`")
            lines.append(f"- got: {cls['detail']}")
            lines.append("")
    return "\n".join(lines)


def update_manifest(meta: dict, pins_rel: str, passed: int, total_run: int, clean: bool) -> Path:
    doc = json.loads(_MANIFEST.read_text(encoding="utf-8"))
    stem = meta["module_stem"]
    for row in doc["modules"]:
        if row.get("stem") != stem:
            continue
        row["status"] = "gated" if clean else "partial"
        row["notes"] = (
            f"{passed}/{total_run} output-oracle pins pass on jacpython "
            "(diff_runner); lanes fix VM gaps from the triage report."
        )
        row["jacpython_results"] = {stem: {"passed": passed, "total": total_run}}
        break
    else:
        doc["modules"].append(
            {
                "stem": stem,
                "gate_type": "oracle",
                "status": "gated" if clean else "partial",
                "oracle_tests": [pins_rel],
                "libtest_snippets": [],
                "notes": f"{passed}/{total_run} output-oracle pins pass on jacpython.",
                "jacpython_results": {stem: {"passed": passed, "total": total_run}},
            }
        )
    doc["module_count"] = len(doc["modules"])
    _MANIFEST.write_text(json.dumps(doc, indent=2) + "\n", encoding="utf-8")
    return _MANIFEST


# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("pins_jac", help=".jac pin file produced by convert_suite.py")
    parser.add_argument("--report", default=None, help="triage report path (default: beside pins)")
    parser.add_argument("--manifest", default=None, help="conformance manifest to update")
    args = parser.parse_args(argv)

    global _MANIFEST
    if args.manifest:
        _MANIFEST = Path(args.manifest)

    pins_file = Path(args.pins_jac)
    if not pins_file.is_file():
        parser.error(f"not a named file: {pins_file}")
    meta_path = pins_file.parent / "conversion.json"
    if not meta_path.is_file():
        # pre-contract sidecar name fallback
        legacy = pins_file.with_name(pins_file.name.replace("_pins.jac", ".conv.json"))
        if legacy.is_file():
            meta_path = legacy
        else:
            parser.error(f"missing conversion sidecar: {pins_file.parent / 'conversion.json'}")
    meta = json.loads(meta_path.read_text(encoding="utf-8"))
    pinned = [e for e in meta["pins"] if e.get("status") == "pinned"]

    marks, timed_out, _stderr = run_pins(pinned)
    elapsed_note = "TIMEOUT at %ds cap" % JAC_TIMEOUT if timed_out else (
        f"{sum(1 for m in marks if m[1] == 'PASS')}/{len(pinned)} marks"
    )
    classifications = classify(marks, pinned, timed_out)

    report = build_report(pins_file, meta, elapsed_note, classifications)
    report_path = Path(args.report) if args.report else pins_file.with_suffix(".triage.md")
    report_path.write_text(_sanitize_report_text(report), encoding="utf-8")

    conformance_path, result_path = write_conformance_and_result(
        pins_file.parent, meta,
        ["diff_runner.py", str(pins_file)], classifications, timed_out, pins_file,
    )

    result_status = "failed" if (classifications or timed_out) else "passed"
    passed = len(pinned) - len(classifications)
    quarantined_count = len(meta["quarantined"]) + sum(
        1 for e in meta["pins"] if e.get("status") == "quarantined"
    )
    manifest_path = update_manifest(
        meta,
        str(pins_file.relative_to(_REPO)) if pins_file.is_relative_to(_REPO) else str(pins_file),
        max(passed, 0),
        len(pinned),
        clean=(not classifications) and quarantined_count == 0 and not timed_out,
    )

    print(f"ran {len(pinned)} pins: "
          f"{max(passed, 0)} passed, {len(classifications)} failed/not-run, {quarantined_count} quarantined")
    print(f"report:      {report_path}")
    print(f"conformance: {conformance_path}")
    print(f"result:      {result_path} (status={result_status})")
    return 0 if result_status == "passed" else 1


if __name__ == "__main__":
    sys.exit(main())
