#!/usr/bin/env python3
"""na_concat -- WORKAROUND(jaseci-labs/jac#7834) for the native build.

`jac nacompile` mis-compiles virtual method dispatch when a base `obj` lives in
an imported module: the override guard misses the cross-module subclass and it
silently devirtualizes to the base slot (or ICEs). Single-file dispatch is
correct even at 10k+ LOC. So until #7834 is fixed we cannot ship the planned
native DAG (marshal -> objects <- ceval) as separate modules.

This tool fuses an ordered set of jac-py native modules into ONE .jac
compilation unit -- stripping the intra-set `import from <sibling> { ... }`
lines (the boundary that trips the bug) so every vtable is visible in-file --
then nacompiles it. Imports of modules OUTSIDE the set are preserved.

REVERT THIS WHOLE FILE and go back to per-module `jac nacompile` of the DAG
once #7834 closes. Track: jac-py/PLAN.md §4 (module-boundary constraint) and
the D4 sizing report.

STATUS (2026-08-01): proven end-to-end. The leaf ICE that blocked this
(`vtable.impl.jac` gep'd an uncoerced any-box receiver) was a DISTINCT bug from
#7834, filed as jac#7835 and fixed in-tree (gep the coerced receiver). With that
fix, `objects.jac` nacompiles again and a fused `objects + ceval-slice + entry`
build links and dispatches a cross-module override CORRECTLY (prints the override
result). #7834 (imported-base silent devirtualization) remains OPEN -- that is
exactly the boundary this concat step routes around. Revert when #7834 closes.

Usage (Python shim -- nacompile is driven as a subprocess the Jac runtime does
not host; mirrors tests/na_cliffs/t7_gate.py):

    PYTHONPATH=jac .venv/bin/python jac-py/tools/na_concat.py \
        jac-py/jacpython/objects.jac jac-py/jacpython/ceval_slice.jac \
        --entry-file jac-py/tests/na_cliffs/driver_entry.jac \
        -o /tmp/jacpython_native
"""
from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys

# `import from <stem> { ... }`  and  `import <stem>;` / `include <stem>;`
_IMPORT_FROM = re.compile(r"^\s*import\s+from\s+([A-Za-z_][\w.]*)\s*\{")
_IMPORT_BARE = re.compile(r"^\s*(?:import|include)\s+([A-Za-z_][\w.]*)\s*;")


def _repo_root() -> str:
    out = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        capture_output=True, text=True, check=True,
    )
    return out.stdout.strip()


def _strip_intra_imports(body: str, sibling_stems: set[str]) -> str:
    """Drop imports that target another module in the concat set; keep the rest."""
    kept: list[str] = []
    lines = body.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        m_from = _IMPORT_FROM.match(line)
        if m_from and m_from.group(1).split(".")[0] in sibling_stems:
            block = [line.strip()]
            if "}" not in line:
                i += 1
                while i < len(lines) and "}" not in lines[i]:
                    block.append(lines[i].strip())
                    i += 1
                if i < len(lines):
                    block.append(lines[i].strip())
            kept.append(f"# [na_concat #7834] stripped: {' '.join(block)}")
            i += 1
            continue
        m_bare = _IMPORT_BARE.match(line)
        if m_bare and m_bare.group(1).split(".")[0] in sibling_stems:
            kept.append(f"# [na_concat #7834] stripped: {line.strip()}")
            i += 1
            continue
        kept.append(line)
        i += 1
    return "\n".join(kept)


def concat(modules: list[str], entry_file: str | None) -> str:
    stems = {os.path.splitext(os.path.basename(m))[0] for m in modules}
    parts = [
        "# GENERATED by jac-py/tools/na_concat.py -- WORKAROUND(jaseci-labs/jac#7834).",
        "# Do not edit; regenerate. Revert to per-module nacompile when #7834 closes.",
    ]
    for m in modules:
        with open(m) as fh:
            body = fh.read()
        parts.append(f"\n# ===== {os.path.relpath(m)} =====")
        parts.append(_strip_intra_imports(body, stems))
    if entry_file:
        with open(entry_file) as fh:
            parts.append(f"\n# ===== entry: {os.path.relpath(entry_file)} =====")
            parts.append(_strip_intra_imports(fh.read(), stems))
    return "\n".join(parts) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("modules", nargs="+", help="native .jac modules in dependency order")
    ap.add_argument("--entry-file", help="a .jac file supplying the `with entry` block")
    ap.add_argument("-o", "--output", default="/tmp/jacpython_native", help="binary path")
    ap.add_argument("--emit", help="also write the fused .jac to this path")
    ap.add_argument("--compile-only", action="store_true", help="stop at object emit (.o)")
    args = ap.parse_args()

    os.chdir(_repo_root())
    fused = concat(args.modules, args.entry_file)
    fused_path = args.emit or "/tmp/jacpython_native_fused.jac"
    with open(fused_path, "w") as fh:
        fh.write(fused)

    out = args.output + (".o" if args.compile_only else "")
    py = os.environ.get("JACPY", ".venv/bin/python")
    env = dict(os.environ, PYTHONPATH="jac")
    proc = subprocess.run(
        [py, "-m", "jaclang", "nacompile", fused_path, "-s", "-o", out],
        capture_output=True, text=True, env=env,
    )
    tail = (proc.stdout + proc.stderr)
    for line in tail.splitlines():
        if re.search(r"emitted|error|E5090|Traceback|Assertion|panic", line, re.I):
            print(line)
    ok = "Object code emitted" in tail and "E5090" not in tail
    print(f"[na_concat] fused={fused_path} -> {out}  {'OK' if ok else 'FAILED'}")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
