"""tokens2jac - emit Jac token model from CPython's Grammar/Tokens.

This is the Jac emit backend for the token metaprogram (PLAN.md P0.4). It reuses
the same token-loading logic as CPython's Tools/build/generate_token.py, then
emits jacpython's na-clean token/location/diagnostic representation shared by the
tokenizer and PEG runtime. Regenerate whenever the pinned CPython tag moves (see
CURRENT.md).

Usage:
    python jac-py/tools/tokens2jac.py            # writes jac-py/jacpython/token_model.jac
    python jac-py/tools/tokens2jac.py --stdout   # print to stdout
    python jac-py/tools/tokens2jac.py --check    # fail if checked-in file is stale
"""

from __future__ import annotations

import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.dirname(os.path.dirname(_HERE))
TOKENS_PATH = os.path.join(_REPO, "reference", "cpython", "Grammar", "Tokens")
OUT_PATH = os.path.join(_REPO, "jac-py", "jacpython", "token_model.jac")

NT_OFFSET = 256


def load_tokens(path: str) -> tuple[list[str], int, dict[str, int]]:
    """Parse Grammar/Tokens into names, ERRORTOKEN index, and spelling map."""
    tok_names: list[str] = []
    string_to_tok: dict[str, int] = {}
    errortoken = 0
    with open(path) as fp:
        for line in fp:
            line = line.strip()
            i = line.find("#")
            if i >= 0:
                line = line[:i].strip()
            if not line:
                continue
            fields = line.split()
            name = fields[0]
            value = len(tok_names)
            if name == "ERRORTOKEN":
                errortoken = value
            if len(fields) > 1:
                string = eval(fields[1])
                string_to_tok[string] = value
            tok_names.append(name)
    return tok_names, errortoken, string_to_tok


def _emit_glob_constants(tok_names: list[str], out: list[str]) -> None:
    parts = [f"{name}: int = {value}" for value, name in enumerate(tok_names)]
    out.append("glob " + parts[0] + ",")
    for part in parts[1:]:
        out.append(f"     {part},")
    out.append(f"     NT_OFFSET: int = {NT_OFFSET},")
    out.append(f"     N_TOKENS: int = {len(tok_names)},")
    out.append("     TOK_NO_LINE: int = -1,")
    out.append("     TOK_NO_COLUMN: int = -1;")
    out.append("")


def _emit_exact_token_types(
    tok_names: list[str], string_to_tok: dict[str, int], out: list[str]
) -> None:
    out.append("glob EXACT_TOKEN_TYPES: dict[str, int] = {")
    for string, value in sorted(string_to_tok.items()):
        name = tok_names[value]
        out.append(f'    "{string}": {name},')
    out.append("};")
    out.append("")


def _emit_token_names(tok_names: list[str], errortoken: int, out: list[str]) -> None:
    out.append("glob TOKEN_NAMES: list[str] = [")
    for value, name in enumerate(tok_names):
        label = name if value < errortoken else f"<{name}>"
        out.append(f'    "{label}",')
    out.append("];")
    out.append("")


def generate(tok_names: list[str], errortoken: int, string_to_tok: dict[str, int]) -> str:
    out: list[str] = []
    out.append('"""jacpython token model.')
    out.append("")
    out.append(
        "GENERATED by jac-py/tools/tokens2jac.py from reference/cpython/Grammar/Tokens"
    )
    out.append("(CPython pin: see CURRENT.md). Do not edit by hand - regenerate instead.")
    out.append("")
    out.append("Coordinate convention (matches CPython 3.14 / compiler_ir.cloc):")
    out.append("  lineno / end_lineno: 1-based line numbers")
    out.append("  col_offset / end_col_offset: 0-based byte offsets into the source line")
    out.append("")
    out.append("Keywords are NAME tokens at the scanner; keyword vs identifier")
    out.append("distinction is enforced by the PEG parser keyword tables (P0.6/P0.7).")
    out.append("SOFT_KEYWORD is a distinct terminal for soft-keyword spellings.")
    out.append('"""')
    out.append("")
    out.append("# na-clean leaf: no imports, no host calls.")
    out.append("")
    out.append("# ---------------- token type ids and tables (module-level glob) ----------------")
    _emit_glob_constants(tok_names, out)
    _emit_exact_token_types(tok_names, string_to_tok, out)
    _emit_token_names(tok_names, errortoken, out)
    out.append("# ---------------- predicates (Include/internal/pycore_token.h) ----------------")
    out.append("def is_terminal(t: int) -> bool {")
    out.append("    return t < NT_OFFSET;")
    out.append("}")
    out.append("")
    out.append("def is_nonterminal(t: int) -> bool {")
    out.append("    return t >= NT_OFFSET;")
    out.append("}")
    out.append("")
    out.append("def is_eof(t: int) -> bool {")
    out.append("    return t == ENDMARKER;")
    out.append("}")
    out.append("")
    out.append("def is_whitespace_token(t: int) -> bool {")
    out.append("    return t == ENDMARKER or t == NEWLINE or t == INDENT or t == DEDENT;")
    out.append("}")
    out.append("")
    out.append("def is_stringlit_token(t: int) -> bool {")
    out.append(
        "    return t == STRING or t == FSTRING_MIDDLE or t == TSTRING_MIDDLE;"
    )
    out.append("}")
    out.append("")
    out.append("def exact_token_type(spelling: str) -> int {")
    out.append("    if spelling in EXACT_TOKEN_TYPES {")
    out.append("        return EXACT_TOKEN_TYPES[spelling];")
    out.append("    }")
    out.append("    return OP;")
    out.append("}")
    out.append("")
    out.append("def token_name(t: int) -> str {")
    out.append("    if t < 0 or t >= len(TOKEN_NAMES) {")
    out.append("        return \"<invalid>\";")
    out.append("    }")
    out.append("    return TOKEN_NAMES[t];")
    out.append("}")
    out.append("")
    out.append("# ---------------- source locations ----------------")
    out.append("obj tok_loc {")
    out.append("    has lineno: int,")
    out.append("        end_lineno: int,")
    out.append("        col_offset: int,")
    out.append("        end_col_offset: int;")
    out.append("}")
    out.append("")
    out.append("def tok_no_loc -> tok_loc {")
    out.append("    return tok_loc(")
    out.append("        lineno=TOK_NO_LINE,")
    out.append("        end_lineno=TOK_NO_LINE,")
    out.append("        col_offset=TOK_NO_COLUMN,")
    out.append("        end_col_offset=TOK_NO_COLUMN")
    out.append("    );")
    out.append("}")
    out.append("")
    out.append("def tok_loc_span(")
    out.append("    lineno: int, end_lineno: int, col_offset: int, end_col_offset: int")
    out.append(") -> tok_loc {")
    out.append("    return tok_loc(")
    out.append("        lineno=lineno,")
    out.append("        end_lineno=end_lineno,")
    out.append("        col_offset=col_offset,")
    out.append("        end_col_offset=end_col_offset")
    out.append("    );")
    out.append("}")
    out.append("")
    out.append("def same_tok_loc(a: tok_loc, b: tok_loc) -> bool {")
    out.append("    if a.lineno != b.lineno {")
    out.append("        return False;")
    out.append("    }")
    out.append("    if a.end_lineno != b.end_lineno {")
    out.append("        return False;")
    out.append("    }")
    out.append("    if a.col_offset != b.col_offset {")
    out.append("        return False;")
    out.append("    }")
    out.append("    if a.end_col_offset != b.end_col_offset {")
    out.append("        return False;")
    out.append("    }")
    out.append("    return True;")
    out.append("}")
    out.append("")
    out.append("# ---------------- token value ----------------")
    out.append("obj tok_token {")
    out.append("    has tok_type: int,")
    out.append("        spelling: str,")
    out.append("        lineno: int,")
    out.append("        col_offset: int,")
    out.append("        end_lineno: int,")
    out.append("        end_col_offset: int,")
    out.append("        level: int = 0,")
    out.append("        metadata: str | None = None;")
    out.append("}")
    out.append("")
    out.append("def token_loc(tok: tok_token) -> tok_loc {")
    out.append("    return tok_loc_span(")
    out.append("        tok.lineno, tok.end_lineno, tok.col_offset, tok.end_col_offset")
    out.append("    );")
    out.append("}")
    out.append("")
    out.append("# ---------------- diagnostics ----------------")
    out.append("obj tok_diag {")
    out.append("    has kind: str,")
    out.append("        message: str,")
    out.append("        loc: tok_loc,")
    out.append("        filename: str = \"<unknown>\";")
    out.append("}")
    out.append("")
    out.append("def mk_diag(kind: str, message: str, loc: tok_loc, filename: str) -> tok_diag {")
    out.append("    return tok_diag(kind=kind, message=message, loc=loc, filename=filename);")
    out.append("}")
    out.append("")
    return "\n".join(out).rstrip() + "\n"


def main(argv: list[str]) -> int:
    tok_names, errortoken, string_to_tok = load_tokens(TOKENS_PATH)
    text = generate(tok_names, errortoken, string_to_tok)
    if "--stdout" in argv:
        sys.stdout.write(text)
        return 0
    if "--check" in argv:
        try:
            with open(OUT_PATH) as fh:
                on_disk = fh.read()
        except FileNotFoundError:
            print(f"{OUT_PATH} missing; run tokens2jac.py to generate it", file=sys.stderr)
            return 1
        if on_disk != text:
            print(f"{OUT_PATH} is stale; regenerate with tokens2jac.py", file=sys.stderr)
            return 1
        print(f"{OUT_PATH} up to date ({len(tok_names)} token types)")
        return 0
    with open(OUT_PATH, "w") as fh:
        fh.write(text)
    print(f"wrote {OUT_PATH} ({len(tok_names)} token types)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
