# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: module_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 27, 2, "", "module_service.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x14module_service.proto"2\n\rMethodRequest\x12\x13\n\x0bmethod_name\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x03(\t" \n\x0eMethodResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2A\n\rModuleService\x12\x30\n\rExecuteMethod\x12\x0e.MethodRequest\x1a\x0f.MethodResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "module_service_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_METHODREQUEST"]._serialized_start = 24
    _globals["_METHODREQUEST"]._serialized_end = 74
    _globals["_METHODRESPONSE"]._serialized_start = 76
    _globals["_METHODRESPONSE"]._serialized_end = 108
    _globals["_MODULESERVICE"]._serialized_start = 110
    _globals["_MODULESERVICE"]._serialized_end = 175
# @@protoc_insertion_point(module_scope)
