# Model Configurations
Model:
  type: PersonalizedHead
  args:
    embedding_length: 768
    ph_nhead: 8
    ph_ff_dim: 512
    batch_first: True
    ph_nlayers: 1
    n_classes: 8

# Model Training Configurations
Trainer:
  name: PersonalizedHead
  n_gpu: 1
  dataloader:
    type: SentenceIntentDataLoader
    args:
      data_dir: data/
      batch_size: 128
      shuffle: true
      validation_split: 0.1
      num_workers: 2
  optimizer:
    type: Adam
    args:
      lr: 0.001
      weight_decay: 0
      amsgrad: true
  loss: nll_loss
  metrics:
    - accuracy
    - top_k_acc
  lr_scheduler:
    type: StepLR
    args:
      step_size: 50
      gamma: 0.1
  trainer:
    epochs: 100
    save_dir: saved/
    save_period: 1
    verbosity: 2
    monitor: min val_loss
    early_stop: 10
    tensorboard: true

# Model Inferencing Configurations
Inference:
  weights: ""
  preprocess:
    type: PreProcessor
    args: {}
  postprocess:
    type: PostProcessor
    args: {}

# # Logger Configurations
# Logger:
#   version: 1
#   disable_existing_loggers: False
#   formatters:
#     simple:
#       format: "%(message)s"
#     datetime:
#       format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
#   handlers:
#     console:
#       class: logging.StreamHandler
#       level: DEBUG
#       formatter: simple
#       stream: ext://sys.stdout
#     info_file_handler:
#       class: logging.handlers.RotatingFileHandler
#       level: INFO
#       formatter: datetime
#       filename: info.log
#       maxBytes: 10485760
#       backupCount: 20
#       encoding: utf8
#   root:
#     level: INFO
#     handlers:
#       - console
#       - info_file_handler
