kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "jaseci.fullname" . }}-db-pvc
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.image.db.storage }}
---