apiVersion: v1
kind: Service
metadata:
  name: summarization
spec:
  selector:
    pod: summarization
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: summarization-up
  namespace: default
data:
  prod_up: |-
    git clone https://github.com/Jaseci-Labs/jaseci.git /jaseci/
    cd /jaseci/jaseci_core/
    source install.sh
    cd /jaseci
    cd /jaseci/jaseci_kit/jaseci_kit/modules/summarization
    uvicorn summarization:serv_actions --host 0.0.0.0 --port 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: summarization
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: summarization
  template:
    metadata:
      labels:
        pod: summarization
      name: summarization
    spec:
      containers:
        - name: summarization
          imagePullPolicy: Always
          image: jaseci/ai-ready-img
          resources:
            requests:
              memory: "2Gi"
            limits:
              memory: "2Gi"
          command: [bash, -c, "source script/prod_up"]
          ports:
            - containerPort: 80
          volumeMounts:
            - name: prod-script
              mountPath: /script

      volumes:
        - name: prod-script
          configMap:
            name: summarization-up
