#!/home/jac/repos/jac-python/.venv/bin/python
"""Generate CPython 3.14 with-statement oracle goldens.

This file is intentionally standalone and has no Jac runtime dependency.
"""
from __future__ import annotations

import dis
import json
from pathlib import Path
import types

OUT = Path(__file__).resolve().parent

FIXTURES = [
    (
        "single_with_as",
        """def f():
    with manager() as resource:
        result = resource.value
""",
        "baseline single item with-as lowering",
    ),
    (
        "two_with_as",
        """def f():
    with first() as left, second() as right:
        result = left.value + right.value
""",
        "two items, both with as bindings; each item contributes its own unwind region",
    ),
    (
        "two_first_as_second_bare",
        """def f():
    with first() as left, second():
        result = left.value
""",
        "two items, first with as binding and second without a target",
    ),
    (
        "single_with_bare",
        """def f():
    with manager():
        result = 1
""",
        "single item with no as binding",
    ),
    (
        "three_with_as",
        """def f():
    with first() as one, second() as two, third() as three:
        result = one.value + two.value + three.value
""",
        "three items, all with as bindings",
    ),
    (
        "nested_with",
        """def f():
    with outer() as outer_resource:
        with inner() as inner_resource:
            result = outer_resource.value + inner_resource.value
""",
        "nested with statements; inner protected region is inside outer body",
    ),
    (
        "with_inside_try_except",
        """def f():
    try:
        with manager() as resource:
            result = resource.value
    except ValueError:
        result = 0
""",
        "with body nested in a try/except protected region",
    ),
    (
        "with_exit_suppresses",
        """def f():
    with suppressing_manager() as resource:
        result = resource.value
""",
        "static bytecode is the same shape; runtime __exit__ return value controls suppression",
    ),
]


def walk_code_objects(value: types.CodeType):
    """Yield every nested code object, recursively, in constant order."""
    yield value
    for constant in value.co_consts:
        if isinstance(constant, types.CodeType):
            yield from walk_code_objects(constant)


def function_code(source: str) -> types.CodeType:
    module = compile(source, "<with-oracle>", "exec")
    candidates = [code for code in walk_code_objects(module) if code.co_name == "f"]
    if len(candidates) != 1:
        raise AssertionError(f"expected one f code object, found {len(candidates)}")
    return candidates[0]


def serializable_argval(value):
    if isinstance(value, types.CodeType):
        return f"<code {value.co_name!r}>"
    try:
        json.dumps(value)
    except TypeError:
        return repr(value)
    return value


def instruction_record(instruction: dis.Instruction):
    return {
        "offset": instruction.offset,
        "opcode": instruction.opcode,
        "opname": instruction.opname,
        "arg": instruction.arg,
        "argval": serializable_argval(instruction.argval),
        "argrepr": instruction.argrepr,
        "starts_line": instruction.starts_line,
        "is_jump_target": instruction.is_jump_target,
    }


def exception_record(entry):
    return {
        "start": entry.start,
        "end": entry.end,
        "target": entry.target,
        "depth": entry.depth,
        "lasti": entry.lasti,
    }


def fixture_record(name: str, source: str, note: str):
    code = function_code(source)
    instructions = [instruction_record(item) for item in dis.get_instructions(code)]
    entries = [exception_record(item) for item in dis.Bytecode(code).exception_entries]
    return {
        "name": name,
        "source": source,
        "note": note,
        "co_name": code.co_name,
        "co_flags": code.co_flags,
        "co_flags_hex": hex(code.co_flags),
        "co_stacksize": code.co_stacksize,
        "co_code_hex": code.co_code.hex(),
        "co_exceptiontable_hex": code.co_exceptiontable.hex(),
        "instructions": instructions,
        "exception_entries": entries,
    }


def render_instruction(item):
    arg = "" if item["arg"] is None else f" {item['arg']}"
    argrepr = f" {item['argrepr']}" if item["argrepr"] else ""
    return f"{item['offset']:04d}: {item['opname']}{arg}{argrepr}"


def render_markdown(records):
    lines = [
        "# Band 6 multi-item and bare `with` CPython 3.14 goldens",
        "",
        "Generated by `dump.py` with `/home/jac/repos/jac-python/.venv/bin/python`.",
        "These are static compile-time records; context-manager runtime behavior is not executed.",
        "Exception entries use CPython's half-open `[start, end)` bytecode offsets.",
        "",
    ]
    for record in records:
        lines.extend(
            [
                f"## {record['name']}",
                "",
                f"{record['note']}.",
                "",
                "### Source",
                "",
                "```python",
                record["source"].rstrip("\\n"),
                "```",
                "",
                "### Code metadata",
                "",
                f"- `co_flags`: `{record['co_flags_hex']}` ({record['co_flags']})",
                f"- `co_stacksize`: `{record['co_stacksize']}`",
                f"- `co_code.hex()`: `{record['co_code_hex']}`",
                f"- `co_exceptiontable.hex()`: `{record['co_exceptiontable_hex']}`",
                "",
                "### Disassembly",
                "",
                "```text",
            ]
        )
        lines.extend(render_instruction(item) for item in record["instructions"])
        lines.extend(["```", "", "### Decoded exception-table entries", ""])
        if record["exception_entries"]:
            lines.extend(
                [
                    "| start | end (exclusive) | target | depth | lasti |",
                    "|---:|---:|---:|---:|:---:|",
                ]
            )
            lines.extend(
                f"| {entry['start']} | {entry['end']} | {entry['target']} | {entry['depth']} | {entry['lasti']} |"
                for entry in record["exception_entries"]
            )
        else:
            lines.append("(none)")
        lines.append("")
    return "\n".join(lines)


def main():
    records = [fixture_record(*fixture) for fixture in FIXTURES]
    (OUT / "goldens.json").write_text(json.dumps(records, indent=2) + "\n")
    (OUT / "goldens.md").write_text(render_markdown(records))
    print(f"wrote {len(records)} fixtures to {OUT}")
    for record in records:
        print(
            f"{record['name']}: code={record['co_code_hex']} "
            f"exceptiontable={record['co_exceptiontable_hex']} "
            f"stack={record['co_stacksize']} flags={record['co_flags_hex']} "
            f"entries={len(record['exception_entries'])}"
        )


if __name__ == "__main__":
    main()
