apiVersion: v1
kind: Service
metadata:
  name: js-t5-sum
spec:
  selector:
    pod: js-t5-sum
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: js-t5-sum-up
  namespace: default
data:
  prod_up: |-
    pip install jaseci-ai-kit==1.3.5.22
    pip install protobuf==3.20.3
    uvicorn jaseci_ai_kit.t5_sum:serv_actions --host 0.0.0.0 --port 80 --workers 4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: js-t5-sum
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: js-t5-sum
  template:
    metadata:
      labels:
        pod: js-t5-sum
      name: js-t5-sum
    spec:
      containers:
        - name: js-t5-sum
          imagePullPolicy: IfNotPresent
          image: jaseci/jaseci-ai-kit:latest
          resources:
            requests:
              memory: "3Gi"
            limits:
              memory: "3Gi"
          command: [bash, -c, "source script/prod_up"]
          ports:
            - containerPort: 80
          volumeMounts:
            - name: prod-script
              mountPath: /script

      volumes:
        - name: prod-script
          configMap:
            name: js-t5-sum-up
