apiVersion: v1
kind: Service
metadata:
  name: jst5
spec:
  selector:
    pod: jst5
  ports:
    - protocol: TCP
      port: 4674
      targetPort: 4674
      name: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jst5-up
  namespace: default
data:
  prod_up: |-
    git clone https://github.com/Jaseci-Labs/jaseci.git /jaseci/
    mv /jaseci/ai_serving/ /;
    cd /ai_serving;
    python3 -m t5.t5_app;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jst5
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: jst5
  template:
    metadata:
      labels:
        pod: jst5
      name: jst5
    spec:
      containers:
        - name: jst5
          imagePullPolicy: IfNotPresent
          image: jaseci/ai-service:t5
          resources:
            requests:
              memory: "4Gi"
            limits:
              memory: "4Gi"
          command: [bash, -c, "source script/prod_up"]
          ports:
            - containerPort: 4674
          volumeMounts:
            - name: prod-script
              mountPath: /script

      volumes:
        - name: prod-script
          configMap:
            name: jst5-up
