# Generated by Django 3.1.14 on 2021-12-21 17:38

from django.db import migrations, models
from django.db.backends.base import schema

from jaseci_serv.jaseci_serv.base.models import JaseciObject

def convert_user_to_j_master(apps, schema_editor):
    """The old user field in jaseci object convert to j_master"""
    db_alias = schema_editor.connection.alias
    JaseciObject = apps.get_model('base', 'JaseciObject')
    for j_object in JaseciObject.objects.using(db_alias).all():
        j_object.j_master = j_object.user.master
        j_object.save()

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GlobalConfig',
            new_name='GlobalVars',
        ),
        migrations.RenameField(
            model_name='jaseciobject',
            old_name='j_owner',
            new_name='j_parent',
        ),
        migrations.AddField(
            model_name='jaseciobject',
            name='j_master',
        ),
        migrations.RunPython(convert_user_to_j_master, migrations.RunPython.noop),

        migrations.RemoveField(
            model_name='jaseciobject',
            name='user',
        ),
        migrations.AddField(
            model_name='jaseciobject',
            name='j_access',
            field=models.CharField(default='private', max_length=15),
        ),
        migrations.AddField(
            model_name='jaseciobject',
            name='j_r_acc_ids',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jaseciobject',
            name='j_rw_acc_ids',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
