# Generated by Django 3.1.14 on 2022-01-22 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_jaseci_1_to_1_3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jaseciobject',
            old_name='name',
            new_name='name_temp'
        ),
        migrations.RenameField(
            model_name='jaseciobject',
            old_name='kind',
            new_name='name'
        ),
        migrations.RenameField(
            model_name='jaseciobject',
            old_name='name_temp',
            new_name='kind'
        )
    ]
