# Generated by Django 3.1.14 on 2022-01-22 16:33

from django.db import migrations
from django.db.models import F

def copy_field(apps, schema_editor):
    MyModel = apps.get_model('base', 'JaseciObject')
    MyModel.objects.all().update(kind=F('j_type'))

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_swap_kind_and_name'),
    ]
    operations = [
        migrations.RunPython(copy_field, migrations.RunPython.noop),
    ]
