glob WIN_WIDTH:int = 640;
glob WIN_HEIGHT:int = 480;
glob TILESIZE:int = 32;
glob FPS:int = 60;

glob ATTACK_LAYER:int = 5;
glob ENEMY_LAYER:int = 4;
glob PLAYER_LAYER:int = 3;
glob BLOCK_LAYER:int = 2;
glob GROUND_LAYER:int = 1;

glob PLAYER_SPEED:int = 3;
glob ENEMY_SPEED:int = 2;

glob RED:tuple = (255, 0, 0);
glob BLACK:tuple = (0, 0, 0);
glob BLUE:tuple = (0, 0, 255);
glob WHITE:tuple = (255, 255, 255);

glob GENERAL_FONT:str = '../fonts/8bitoperator_jve.ttf';