#!/bin/bash

export CLASSPATH="$PWD/jaseci/core/jac/antlr4-tool/antlr-4.8-complete.jar:$CLASSPATH"
java -Xmx500M -cp \"$PWD/jaseci/core/jac/antlr4-tool/antlr-4.8-complete.jar:$CLASSPATH\" org.antlr.v4.Tool -Dlanguage=Python3 -o $PWD/jaseci/core/jac/_jac_gen $PWD/jaseci/core/jac/jac.g4