apiVersion: v1
kind: Service
metadata:
  name: jsuse-encoder
spec:
  selector:
    pod: jsuse-encoder
  ports:
    - protocol: TCP
      port: 4673
      targetPort: 4673
      name: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jsuse-encoder-up
  namespace: default
data:
  prod_up: |-
    git clone https://github.com/Jaseci-Labs/jaseci.git /jaseci/
    mv /jaseci/ai_serving/ /;
    cd /ai_serving;
    python3 -m use_encoder.use_encoder_app;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsuse-encoder
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: jsuse-encoder
  template:
    metadata:
      labels:
        pod: jsuse-encoder
      name: jsuse-encoder
    spec:
      containers:
        - name: jsuse-encoder
          imagePullPolicy: IfNotPresent
          image: jaseci/ai-service:use-encoder
          resources:
            requests:
              memory: "2Gi"
            limits:
              memory: "2Gi"
          command: [bash, -c, "source script/prod_up"]
          ports:
            - containerPort: 4673
          volumeMounts:
            - name: prod-script
              mountPath: /script

      volumes:
        - name: prod-script
          configMap:
            name: jsuse-encoder-up