# 1. Namespace: littlex
apiVersion: v1
kind: Namespace
metadata:
  name: littlex
---
# 2. ServiceAccount: jac-cloud-sa (in the littlex namespace)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jac-cloud-sa
  namespace: littlex
---
# 3. ClusterRole: Define permissions for the jac-cloud system
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jac-cloud-cluster-role
rules:
  # Core Kubernetes resources permissions
  - apiGroups: [""] 
    resources:
      - "namespaces"
      - "pods"
      - "services"
      - "configmaps"
    verbs: ["get", "list", "create", "delete", "watch", "patch", "update"]

  # ServiceAccount permissions
  - apiGroups: [""] 
    resources: ["serviceaccounts"]
    verbs: ["get", "list", "create", "delete", "watch", "patch", "update"]

  # RBAC permissions
  - apiGroups: ["rbac.authorization.k8s.io"] 
    resources: ["roles", "rolebindings"]
    verbs: ["get", "list", "create", "delete", "watch", "patch", "update"]

  # Apps API group for managing deployments
  - apiGroups: ["apps"] 
    resources: ["deployments"]
    verbs: ["get", "list", "create", "delete", "watch", "patch", "update"]

  # Allow access to secrets (e.g., for OpenAI API key)
  - apiGroups: [""] 
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
# 4. ClusterRoleBinding: Bind ClusterRole to the ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jac-cloud-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: jac-cloud-sa
    namespace: littlex
roleRef:
  kind: ClusterRole
  name: jac-cloud-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
# 5. Deployment: jac-cloud application deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jac-cloud
  namespace: littlex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jac-cloud
  template:
    metadata:
      labels:
        app: jac-cloud
    spec:
      # Attach the ServiceAccount for RBAC
      serviceAccountName: jac-cloud-sa
      containers:
      - name: jac-cloud
        image: ashishmahendra/littlex:0.1
        imagePullPolicy: Always

        # Environment variables for dynamic configuration
        env:
          - name: CONFIG_FILE_PATH
            value: "/cfg/module_config.json" 
          - name: NAMESPACE
            value: "littlex"
          - name: CONFIGMAP_NAME
            value: "module-config"
          - name: FILE_NAME
            value: "littleX_BE/littleX_full.jac"
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: openai-secret
                key: openai-key

        # Mount ConfigMap for application configuration
        volumeMounts:
          - name: config-vol
            mountPath: /cfg
      volumes:
        - name: config-vol
          configMap:
            name: module-config
            items:
              - key: module_config.json
                path: module_config.json

      # Restart policy
      restartPolicy: Always
---
# 6. Secret: OpenAI API key (optional example for completeness)
apiVersion: v1
kind: Secret
metadata:
  name: openai-secret
  namespace: littlex
type: Opaque
data:
  openai-key: "c2stcHJvai0xTnRDVGpoUDg4YTFCcFU0cXUyclQzQmxia0ZKRjh2NndqbHgzZDVRWWNrMjBubjY="
