# 1. Namespace: littlex
apiVersion: v1
kind: Namespace
metadata:
  name: littlex

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: jac-cloud
  namespace: littlex
data:
  init.sh: |
    #!/bin/bash
    set -e
    echo "=== Starting jac-cloud Pod Initialization ==="

    NAMESPACE=${NAMESPACE:-default}
    CONFIGMAP_NAME=${CONFIGMAP_NAME:-module-config}
    FILE_NAME=${FILE_NAME:-example.jac}

    echo "Using Namespace: $NAMESPACE"
    echo "Running Jac File: $FILE_NAME"

    jac serve "$FILE_NAME" || exit 1
  config.json: |-
    {
      "numpy": {
        "lib_mem_size_req": "100Mi",
        "dependency": [],
        "lib_cpu_req": "500m",
        "load_type": "remote"
      },
      "transformers": {
        "lib_mem_size_req": "2000Mi",
        "dependency": [
          "torch",
          "transformers"
        ],
        "lib_cpu_req": "1.0",
        "load_type": "remote"
      },
      "sentence_transformers": {
        "lib_mem_size_req": "2000Mi",
        "dependency": [
          "sentence-transformers"
        ],
        "lib_cpu_req": "1.0",
        "load_type": "remote"
      }
    }

---

# 5. Deployment: jac-cloud application deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jac-cloud
  namespace: littlex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jac-cloud
  template:
    metadata:
      labels:
        app: jac-cloud
    spec:
      containers:
      - name: jac-cloud
        image: python:3.12-slim  # Use the Python base image
        imagePullPolicy: IfNotPresent

        command: ["/bin/sh", "-c"]
        envFrom:
        - secretRef:
            name: jac-cloud-envs
            optional: true
        args:
          - |
            echo "Installing dependencies..."
            apt-get update && apt-get install -y --no-install-recommends git && apt-get clean && rm -rf /var/lib/apt/lists/*
            echo "Cloning littleX repository..."
            git clone --branch main --depth 1 https://github.com/Jaseci-Labs/littleX.git /root/littleX
            echo "Installing Python dependencies..."
            pip install --no-cache-dir -r /root/littleX/littleX_BE/requirements.txt openai

            git clone --branch enhancements/pod-manager https://github.com/Jaseci-Labs/jaseci.git /root/jaseci
            pip install /root/jaseci/jac-splice-orc/.

            echo "Starting initialization script..."
            /bin/bash /app/init.sh

        # Environment variables for dynamic configuration
        env:
          - name: MODULE_CONFIG_PATH
            value: "/cfg/config.json"
          - name: NAMESPACE
            value: "littlex"
          - name: CONFIGMAP_NAME
            value: "module-config"
          - name: FILE_NAME
            value: "/root/littleX/littleX_BE/_archive/littleX_full.jac"

        # Mount ConfigMap for application configuration
        volumeMounts:
          - name: jac-cloud-config
            mountPath: /cfg
          - name: jac-cloud-init
            mountPath: /app

      volumes:
        - name: jac-cloud-config
          configMap:
            name: jac-cloud
            items:
              - key: config.json
                path: config.json
        - name: jac-cloud-init
          configMap:
            name: jac-cloud
            items:
              - key: init.sh
                path: init.sh

      # Restart policy
      restartPolicy: Always

---

apiVersion: v1
kind: Secret
metadata:
  name: jac-cloud-envs
  namespace: littlex
type: Opaque
data:
  OPENAI_API_KEY: ""