#!/bin/bash
PODN=jaseci
if [[ $1 ]]; then
    PODN=$1
fi

for podname in $(kubectl get pods -l pod=$PODN -o json| jq -r '.items[].metadata.name'); do kubectl cp jaseci_serv ${podname}:/; echo "Copy code to pod and test"; kubectl cp jaseci_core ${podname}:/;  kubectl exec -it ${podname} -- bash -c "cd jaseci_core; source install_live.sh"; done
