#!/bin/bash

find . -name "*pycache*" -exec rm -r {} \;
find . -name "migrations" -exec rm -r {} \;
find . -name "db.sqlite3" -exec rm {} \;
find . -name ".antlr" -exec rm -r {} \;
find . -name ".DS_Store" -exec rm -r {} \;
find . -name "*pythontex-files*" -exec rm -r {} \;
find ./book -type f \( -iname \*.aux -o -iname \*.bbl -o -iname \*.f\* -o -iname \*.gl\* -o -iname \*.blg -o -iname \*.idx -o -iname \*.ind -o -iname \*.log -o -iname \*.pytxcode -o -iname \*.synctex.gz -o -iname \*.toc -o -iname \*.bcf -o -iname \*.ilg -o -iname \*.xml -o -iname \*.ptc \) -exec rm -r {} \;
rm -rf jaseci/docs/build/*
rm -rf jaseci/core/jac/_jac_gen
rm -rf jaseci/core/jac/.antlr

git add --all .
git commit -m "$1"
git push origin
