#!/bin/bash
PODN=jaseci
if [[ $1 ]]; then
    PODN=$1
fi

for podname in $(kubectl get pods -l pod=$PODN -o json| jq -r '.items[].metadata.name'); do kubectl cp jaseci_serv ${podname}:/; echo "Copy code to pod and test"; kubectl cp jaseci_core ${podname}:/;  kubectl exec -it ${podname} -- bash -c "cd jaseci_core; source install.sh"; kubectl exec -it ${podname} -- bash -c "cd jaseci_serv; python3 manage.py test --parallel --failfast -v 0 && flake8 --exclude=settings.py,*migrations*,_jac_gen"; done
