apiVersion: v1
kind: Service
metadata:
  name: tinybox
spec:
  selector:
    pod: tinybox
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinybox
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: tinybox
  template:
    metadata:
      labels:
        pod: tinybox
      name: tinybox
    spec:
      containers:
        - name: tinybox
          image: python:3
          command: ["/bin/sleep", "3650d"]
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
