apiVersion: v1
kind: Service
metadata:
  name: bi-enc
spec:
  selector:
    pod: bi-enc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bi-enc-up
  namespace: default
data:
  prod_up: |-
    git clone https://github.com/Jaseci-Labs/jaseci.git /jaseci/
    cd /jaseci/jaseci_core/
    source install.sh
    cd /jaseci/jaseci_ai_kit/
    source install.sh
    cd /jaseci/jaseci_ai_kit/jaseci_ai_kit/modules/encoders
    uvicorn jaseci_ai_kit.bi_enc:serv_actions --host 0.0.0.0 --port 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bi-enc
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: bi-enc
  template:
    metadata:
      labels:
        pod: bi-enc
      name: bi-enc
    spec:
      containers:
        - name: bi-enc
          imagePullPolicy: IfNotPresent
          image: jaseci/jaseci-ai-kit:latest
          resources:
            requests:
              memory: "2Gi"
            limits:
              memory: "2Gi"
          command: [bash, -c, "source script/prod_up"]
          ports:
            - containerPort: 80
          volumeMounts:
            - name: prod-script
              mountPath: /script

      volumes:
        - name: prod-script
          configMap:
            name: bi-enc-up
