apiVersion: v1
kind: Service
metadata:
  name: cl-summer
spec:
  selector:
    pod: cl-summer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cl-summer-up
  namespace: default
data:
  prod_up: |-
    git clone https://github.com/Jaseci-Labs/jaseci.git /jaseci/
    cd /jaseci/jaseci_core/
    source install.sh
    cd /jaseci
    cd /jaseci/jaseci_ai_kit/jaseci_ai_kit/modules/cl_summer
    uvicorn jaseci_ai_kit.cl_summer:serv_actions --host 0.0.0.0 --port 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cl-summer
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: cl-summer
  template:
    metadata:
      labels:
        pod: cl-summer
      name: cl-summer
    spec:
      containers:
        - name: cl-summer
          imagePullPolicy: IfNotPresent
          image: jaseci/jaseci-ai-kit:latest
          resources:
            requests:
              memory: "2Gi"
            limits:
              memory: "2Gi"
          command: [bash, -c, "source script/prod_up"]
          ports:
            - containerPort: 80
          volumeMounts:
            - name: prod-script
              mountPath: /script

      volumes:
        - name: prod-script
          configMap:
            name: cl-summer-up
