apiVersion: v1
kind: Service
metadata:
  name: pdf-ext
spec:
  selector:
    pod: pdf-ext
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pdf-ext-up
  namespace: default
data:
  prod_up: |-
    git clone https://github.com/Jaseci-Labs/jaseci.git /jaseci/
    cd /jaseci/jaseci_core/
    source install.sh
    cd /jaseci/jaseci_ai_kit
    source install.sh
    cd /jaseci/jaseci_ai_kit/jaseci_ai_kit/modules/pdf_ext
    uvicorn jaseci_ai_kit.pdf_ext:serv_actions --host 0.0.0.0 --port 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-ext
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: pdf-ext
  template:
    metadata:
      labels:
        pod: pdf-ext
      name: pdf-ext
    spec:
      containers:
        - name: pdf-ext
          image: jaseci/jaseci-ai-kit:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "3Gi"
            limits:
              memory: "3Gi"
          command: [bash, -c, "source script/prod_up"]
          ports:
            - containerPort: 80
          volumeMounts:
            - name: prod-script
              mountPath: /script

      volumes:
        - name: prod-script
          configMap:
            name: pdf-ext-up
