apiVersion: v1
kind: Service
metadata:
  name: tfm-ner
spec:
  selector:
    pod: tfm-ner
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tfm-ner-up
  namespace: default
data:
  prod_up: |-
    git clone https://github.com/Jaseci-Labs/jaseci.git /jaseci/
    pip install datasets
    cd /jaseci/jaseci_core/
    source install.sh
    cd /jaseci/jaseci_ai_kit/
    source install.sh
    cd /jaseci/jaseci_ai_kit/jaseci_ai_kit/modules/tfm_ner
    uvicorn jaseci_ai_kit.tfm_ner:serv_actions --host 0.0.0.0 --port 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfm-ner
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: tfm-ner
  template:
    metadata:
      labels:
        pod: tfm-ner
      name: tfm-ner
    spec:
      containers:
        - name: tfm-ner
          imagePullPolicy: IfNotPresent
          image: jaseci/jaseci-ai-kit:latest
          resources:
            requests:
              memory: "3Gi"
            limits:
              memory: "3Gi"
          command: [bash, -c, "source script/prod_up"]
          ports:
            - containerPort: 80
          volumeMounts:
            - name: prod-script
              mountPath: /script

      volumes:
        - name: prod-script
          configMap:
            name: tfm-ner-up
