Model:
  embedding_length: 512
  ph_nheads: 8
  ph_ff_dim: 512
  batch_first: True
  ph_nlayers: 1
  n_classes: 8

Logger:
  version: 1
  disable_existing_loggers: False
  formatters:
    simple:
      format: "%(message)s"
    datetime:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
    info_file_handler:
      class: logging.handlers.RotatingFileHandler
      level: INFO
      formatter: datetime
      filename: info.log
      maxBytes: 10485760
      backupCount: 20
      encoding: utf8
  root:
    level: INFO
    handlers:
      - console
      - info_file_handler
