apiVersion: v1
kind: Service
metadata:
  name: jsbart
spec:
  selector:
    pod: jsbart
  ports:
    - protocol: TCP
      port: 4671
      targetPort: 4671
      name: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jsbart-up
  namespace: default
data:
  prod_up: |-
    git clone https://github.com/Jaseci-Labs/jaseci.git /jaseci/
    mv /jaseci/ai_serving/ /;
    cd /ai_serving;
    python3 -m bart.bart_app;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsbart
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: jsbart
  template:
    metadata:
      labels:
        pod: jsbart
      name: jsbart
    spec:
      containers:
        - name: jsbart
          image: jaseci/ai-service:bart
          resources:
            requests:
              memory: "4Gi"
            limits:
              memory: "4Gi"
          command: [bash, -c, "source script/prod_up"]
          ports:
            - containerPort: 4671
          volumeMounts:
            - name: prod-script
              mountPath: /script

      volumes:
        - name: prod-script
          configMap:
            name: jsbart-up
