site_name: The Jac Programming Language and Jaseci Stack
site_url: https://jac-lang.org
repo_url: https://github.com/Jaseci-Labs/jaseci
edit_uri: edit/main/docs/docs
use_directory_urls: true
nav:
  - Learn:
    - Getting Started: "learn/getting_started.md"
    - Tour of Jac/Jaseci: "learn/introduction.md"
    - Learn By Example:
      - LittleX (your own twitter):
        - "learn/examples/littleX/overview.md"
        - "learn/examples/littleX/tutorial.md"
        - "learn/examples/littleX/quickstart.md"
      - RAG-based Conversational Chatbot:
        - "learn/examples/rag_chatbot/readme.md"
        - "learn/examples/rag_chatbot/1_setting-up-jac-cloud.md"
        - "learn/examples/rag_chatbot/2_building-a-rag-chatbot.md"
        - "learn/examples/rag_chatbot/3_rag-dialogue-routing-chatbot.md"
      - AI driven Applications:
        - "learn/examples/mtp_examples/rpg_game.md"
        - "learn/examples/mtp_examples/fantasy_trading_game.md"
    - Learn Jac Language:
      - Jac in 2 Minutes: "learn/jac_in_a_flash.md"
      - The Jac Book: "jac_book/index.md"
      - Understanding Object-Spatial:
        - "learn/data_spatial/nodes_and_edges.md" # Introduction to DS primitives
        - "learn/data_spatial/walkers.md" # Walker
        - "learn/data_spatial/filtering.md" # Filtering
        - "learn/data_spatial/sequence.md"
      - FAQ: "learn/data_spatial/FAQ.md" # faq
    - Jac Cloud Guide:
      - "learn/jac-cloud/introduction.md"
      - "learn/jac-cloud/quickstart.md"
      - Core Features:
        - "learn/jac-cloud/permission.md"
        - "learn/jac-cloud/logging.md"
        - "learn/jac-cloud/env_vars.md"
      - Real-time & Async:
        - "learn/jac-cloud/websocket.md"
        - "learn/jac-cloud/scheduler.md"
        - "learn/jac-cloud/async_walker.md"
        - "learn/jac-cloud/webhook.md"
      - Operations:
        - "learn/jac-cloud/deployment.md"
    - Jac AI Programming Guides:
        - "learn/jac-mtllm/with_llm.md"
        - Quick Start Guide: "learn/jac-mtllm/quickstart.md"
        - Models: "learn/jac-mtllm/model_declaration.md"
        - Usage of MTP: "learn/jac-mtllm/usage.md"
        - Using Multimodal models: "learn/jac-mtllm/multimodality.md"
        - Bring your own LM: "learn/jac-mtllm/create_own_lm.md"
        - Python MTLLM Interface: "learn/jac-mtllm/python_integration.md"
    - Tooling:
      - "learn/tools/cli.md"
    - Specifications:
      - Object-Spatial Programming Specification: "learn/dspfoundation.md"
      - Full Language Specification: "learn/jac_ref.md"

  - Jac Book (WIP):
    - Introduction: "jac_book/index.md"
    - Chapter 1 - Welcome to Jac: "jac_book/chapter_1.md"
    - Chapter 2 - Setting Up Your Jac Environment: "jac_book/chapter_2.md"
    - Chapter 3 - Familiar Syntax with New Semantics: "jac_book/chapter_3.md"
    - Chapter 4 - Data Structures and Collections: "jac_book/chapter_4.md"
    - Chapter 5 - Object-Oriented Programming Enhanced: "jac_book/chapter_5.md"
    - Chapter 6 - Introduction to Object-Spatial Concepts: "jac_book/chapter_6.md"
    - Chapter 7 - Nodes and Edges: "jac_book/chapter_7.md"
    - Chapter 8 - Walkers - Mobile Computation: "jac_book/chapter_8.md"
    - Chapter 9 - Graph Traversal and Filtering: "jac_book/chapter_9.md"
    - Chapter 10 - Automatic Persistence: "jac_book/chapter_10.md"
    - Chapter 11 - Multi-User Support: "jac_book/chapter_11.md"
    - Chapter 12 - Distributed Systems with Jac: "jac_book/chapter_12.md"
    - Chapter 13 - Asynchronous Operations: "jac_book/chapter_13.md"
    - Chapter 14 - Advanced Walker Patterns: "jac_book/chapter_14.md"
    - Chapter 15 - Python Interoperability: "jac_book/chapter_15.md"
    - Chapter 16 - Type System Deep Dive: "jac_book/chapter_16.md"
    - Chapter 17 - Project - Building a Social Network: "jac_book/chapter_17.md"
    - Chapter 18 - Project - Distributed Task Queue: "jac_book/chapter_18.md"
    - Chapter 19 - Best Practices and Performance Tuning: "jac_book/chapter_19.md"
    - Chapter 20 - Quick Reference: "jac_book/chapter_20.md"
    - Chapter 21 - Best Practices: "jac_book/chapter_21.md"

  - Internals:
    - Contributing: "internals/contrib.md"
    - Design Docs and Guides:
      - Compiler/Runtime Design: "internals/internals.md"
      - Static Compilation:
        - Sym Table Design Docs:
          - "internals/symbol_tables/index.md"
          - "internals/symbol_tables/structure.md"
          - "internals/symbol_tables/building.md"
          - "internals/symbol_tables/def_use.md"
          - "internals/symbol_tables/linking.md"
          - "internals/symbol_tables/resolution.md"
        - UniIR Nodes: "internals/uniir_node.md"
      - Runtime Plugin Interface: "internals/jac_plugins.md"
    - Planning Specs and Docs:
      - Language Ref Roadmap: "internals/planning_specs/ref_roadmap.md"
      - Error System: "internals/planning_specs/error_system.md"
      - Formatter System: "internals/planning_specs/formatter_system.md"
      - Native Type System:
        - Introduction: "internals/planning_specs/native_type_system/index.md"
        - Architecture: "internals/planning_specs/native_type_system/architecture.md"
        - Type Representation: "internals/planning_specs/native_type_system/type_representation.md"
        - Type Resolution: "internals/planning_specs/native_type_system/type_resolution.md"
        - Type Rules: "internals/planning_specs/native_type_system/type_rules.md"
        - Type Inference: "internals/planning_specs/native_type_system/type_inference.md"
        - Compiler Integration: "internals/planning_specs/native_type_system/compiler_integration.md"
        - Let's Build: "internals/planning_specs/native_type_system/lets_build.md"

  - Community Hub:
    - Roadmap: "communityhub/roadmap.md"
    - Release Notes: "communityhub/release_notes.md"
    - Breaking Changes: "communityhub/breaking_changes.md"
    - Fun Stuff:
      - Project Ideas:
        - "communityhub/fun/projects.md"
        - "communityhub/fun/p1.md"
        - "communityhub/fun/p2.md"
        - "communityhub/fun/p3.md"

  - Jac Playground:
    - Playground: "playground/index.html"

theme:
  logo: "assets/logo.png"
  name: "material"
  palette:
    scheme: "slate"
    primary: "black"
    accent: "orange"
  font:
    text: "Roboto"
    code: "Roboto Mono"
  features:
    - content.code.copy
    - content.action.edit
    - content.action.view
    - navigation.instant: false
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.footer
    # - navigation.expand
    # - navigation.sections
    - navigation.top
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: material/fire
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      pygments_style: "autumn"
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: [".", "../"]
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - toc:
        permalink: "#"


extra_css:
  - extra.css

extra:
  generator: false
  social:
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@squidfunk
copyright: Copyright &copy; 2023 - 2024 Jac Hackers Everwhere

extra_javascript:
  - assets/mathjax-config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/pyodide/v0.27.0/full/pyodide.js
  - https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.js
  - https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.52.2/min/vs/loader.min.js
  - js/jac.monarch.js
  - js/run-code.js

plugins:
  - search
  - open-in-new-tab
  - mkdocs-video:
      is_video: True
      video_autoplay: True
      # video_loop: True
      video_controls: False
  - mkdocs-simple-hooks:
      hooks:
        on_pre_build: scripts.handle_jac_compile_data:pre_build_hook
