apiVersion: v1
kind: Service
metadata:
  name: jaseci-ai-service
spec:
  selector:
    pod: jaseci-ai-service
  ports:
    - protocol: TCP
      port: 4673
      targetPort: 4673
      name: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jaseci-ai-service-up
  namespace: default
data:
  prod_up: |-
    git clone https://github.com/Jaseci-Labs/jaseci.git;
    mv jaseci/ai_serving/ /;
    cd /ai_serving;
    python3 -m jaseci_ai_service.JaseciAIService;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaseci-ai-service
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: jaseci-ai-service
  template:
    metadata:
      labels:
        pod: jaseci-ai-service
      name: jaseci-ai-service
    spec:
      containers:
        - name: jaseci-ai-service
          imagePullPolicy: IfNotPresent
          image: jaseci-ai-service:latest
          resources:
            requests:
              memory: "2Gi"
            limits:
              memory: "2Gi"
          command: [bash, -c, "source script/prod_up"]
          ports:
            - containerPort: 4673
          volumeMounts:
            - name: prod-script
              mountPath: /script

      volumes:
        - name: prod-script
          configMap:
            name: jaseci-ai-service-up
