name: Linting and Pre-commit checks for jac-cloud

on:
  pull_request:
    paths:
      - "jac-cloud/**"
  push:
    branches:
      - main
    paths:
      - "jac-cloud/**"

jobs:
  pre-commit-cloud:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: jac-cloud
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.13

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit hooks
        run: pre-commit run --files $(find . -type f)
