name: Run tests for jac-streamlit

on:
  pull_request:
    paths:
      - "tool_plugins/streamlit/**"
  push:
    branches:
      - main
    paths:
      - "tool_plugins/streamlit/**"

jobs:
    test-streamlit:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: tool_plugins/streamlit
        steps:
            - name: Check out code
              uses: actions/checkout@v2

            - name: Set up Python 3.12
              uses: actions/setup-python@v2
              with:
                python-version: 3.12

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -e .
                pip install pytest

            - name: Install Plugin
              run: pip install -e .

            - name: Run tests
              run: pytest
