name: Run tests for jac-splice-orc

on:
  pull_request:
    paths:
      - "jac-splice-orc/**"
  push:
    branches:
      - main
    paths:
      - "jac-splice-orc/**"

jobs:
  test-jaclang:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: jac-splice-orc
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install grpcio-tools pytest httpx

      - name: Set environment for testing
        run: |
          echo "TEST_ENV=true" >> $GITHUB_ENV
      # - name: Run tests
      #   run: pytest -x
