name: Build and Push to DockerHub

on:
  push:
    tags:
      - "*"

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to dockerhub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      # login to dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # a little string manipulation to get the tag number without the leading letter v
      - name: Set versions
        uses: actions/github-script@v4
        id: set_version
        with:
          script: |
            const tag = context.ref.substring(10)
            const no_v_tag = tag.replace('v', '')
            core.setOutput('no-v-tag', no_v_tag)

      # build the image and push to docker hub
      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./support/docker/
          tags: |
            jaseci/jaseci:${{steps.set_version.outputs.no-v-tag}}
          build-args: |
            JASECI_VERSION=${{steps.set_version.outputs.no-v-tag}}
            JASECI_SERV_VERSION=${{steps.set_version.outputs.no-v-tag}}
          file: ./support/docker/jaseci.Dockerfile

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}