name: Build and Push to DockerHub

on:
  push:
    tags:
      - "*"

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to dockerhub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      # login to dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # a little string manipulation to get the tag number without the leading letter v
      - name: Set versions
        uses: actions/github-script@v4
        id: set_version
        with:
          script: |
            const tag = context.ref.substring(10)
            const no_v_tag = tag.replace('v', '')
            core.setOutput('no-v-tag', no_v_tag)

      # build the image and push to docker hub
      # 1. jaseci 
      - name: Build and push image -- Jaseci
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./support/docker/
          tags: |
            jaseci/jaseci:${{steps.set_version.outputs.no-v-tag}}
          build-args: |
            JASECI_PYPI_VERSION=${{steps.set_version.outputs.no-v-tag}}
            JASECI_SERV_PYPI_VERSION=${{steps.set_version.outputs.no-v-tag}}
          file: ./support/docker/jaseci.Dockerfile

      # 2. jaseci with jaseci_ai_kit
      - name: Build and push image -- Jaseci with jaseci-ai-kit
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./support/docker/
          tags: |
            jaseci/jaseci-ai:${{steps.set_version.outputs.no-v-tag}}
          build-args: |
            JASECI_PYPI_VERSION=${{steps.set_version.outputs.no-v-tag}}
            JASECI_SERV_PYPI_VERSION=${{steps.set_version.outputs.no-v-tag}}
            JASECI_AI_KIT_PYPI_VERSION=${{steps.set_version.outputs.no-v-tag}}
            BUILD_WITH_AI=1
          file: ./support/docker/jaseci.Dockerfile