# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Jaseci_core - Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
         pip install build
         pip install twine
         
#     - name: Install Jaseci
#       run: |
#         source jaseci_core/install.sh
#     - name: check Jaseci
#       run: |
#         jsctl
#     - name: Test Jaseci Setup
#       run: |
#         source jaseci_core/test.sh

    - name: Build package
      run: python -m build jaseci_core/ --outdir /home/runner/work/jaseci/jaseci/dist
    
    - name: Upload Package
      run: twine upload /home/runner/work/jaseci/jaseci/dist/* --username bharat.saini.bcs --password ${{ secrets.PASSWORD }}
    
#     - name: Publish package
#       uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
#       with:
#         user: __token__
#         password:  ${{ secrets.BHARAT_PYPI_API_TOKEN }}
#         verbose: true
