name: Jaseci_core - Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8==3.7.9 isort
        
    - name: Install Jaseci
      run: |
        pip3 install jaseci_core/
    - name: check Jaseci
      run: |
        jsctl
    - name: Lint Jaseci
      continue-on-error: true
      run: |
        flake8 --exclude=settings.py,*migrations*,jac_parse,ci_app
    - name: Test Jaseci Setup
      if: always()
      run: |
        cd jaseci_core/
        python3 -m unittest discover jaseci/ --failfast -p "test_$1*.py"
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.6
      with:
        projectBaseDir: .
    


        
