name: jskit regression test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8==3.7.9 isort
        cd support/ai_ready_img
        pip3 install -r requirements.txt
        
    - name: Install jaseci_core
      run: |
        pip3 install jaseci_core/
    - name: Verify installation
      run: |
        jsctl

    - name: Test biencoder
      continue-on-error: true
      run: |
        cd jskit/encoders/
        python3 -m unittest discover . -p "test_*.py"

    - name: Test entity_extraction
      run: |
        cd jskit/entity_extraction/
        python3 -m unittest discover . -p "test_*.py"

    - name: Test fasttext
      run: |
        cd jskit/fasttext/
        python3 -m unittest discover . -p "test_*.py"

    - name: Test text_segmenter
      run: |
        cd jskit/text_segmenter/
        python3 -m unittest discover . -p "test_*.py"

    - name: Test use_enc
      run: |
        cd jskit/use_enc/
        python3 -m unittest discover . -p "test_*.py"

    - name: Test use__qa
      run: |
        cd jskit/use_enc/
        python3 -m unittest discover . -p "test_*.py"
