# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application - Test Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
    - name: Install Jaseci
      run: |
        pwd
        ls -l
        chmod +x /jaseci_core/install.sh
        ./jaseci_core/install.sh
        
    - name: Setup Jaseci
      run: |
        python setup.py
        
    - name: Test Jaseci
      run: |
        chmod +x /jaseci_core/test.sh
        ./jaseci_core/test.sh
