name: VSCode Extension CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: cd jac/support/vscode_ext/jac && npm install
      - run: sudo apt-get update && sudo apt-get install -y xvfb
      - run: npx @vscode/test-electron --install-extension ms-python.python
      - run: cd jac/support/vscode_ext/jac && xvfb-run -a npm test