name: VSCode Extension CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd jac/support/vscode_ext/jac
          npm install
          npm install --save-dev @vscode/test-electron

      - run: sudo apt-get update && sudo apt-get install -y xvfb

      - name: Install code-server (VS Code CLI)
        run: |
          curl -fsSL https://code-server.dev/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build extension
        run: |
          cd jac/support/vscode_ext/jac
          ./scripts/build.sh

      - name: Run tests
        run: |
          cd jac/support/vscode_ext/jac
          xvfb-run -a npm test
