apiVersion: v1
kind: Service
metadata:
  name: flair-ner
spec:
  selector:
    pod: flair-ner
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flair-ner-up
  namespace: default
data:
  prod_up: |-
    git clone https://github.com/Jaseci-Labs/jaseci.git /jaseci/
    cd /jaseci/jaseci_core/
    source install.sh
    cd /jaseci/jaseci_kit/
    source install.sh
    pip install flair==0.10
    cd /jaseci/jaseci_kit/jaseci_kit/modules/entity_extraction
    uvicorn jaseci_kit.ent_ext:serv_actions --host 0.0.0.0 --port 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flair-ner
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: flair-ner
  template:
    metadata:
      labels:
        pod: flair-ner
      name: flair-ner
    spec:
      containers:
        - name: flair-ner
          imagePullPolicy: IfNotPresent
          image: jaseci/jaseci-kit:latest
          resources:
            requests:
              memory: "3Gi"
          command: [bash, -c, "source script/prod_up"]
          ports:
            - containerPort: 80
          volumeMounts:
            - name: prod-script
              mountPath: /script

      volumes:
        - name: prod-script
          configMap:
            name: flair-ner-up
